// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/createClient.ts";
import * as $$$$$$$$$1 from "./actions/getImoveis.ts";
import * as $$$$$$$$$$$0 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$3 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/BannerCTA.tsx";
import * as $$$$$$1 from "./sections/BlogPost.tsx";
import * as $$$$$$2 from "./sections/BlogPosts.tsx";
import * as $$$$$$3 from "./sections/BuscaImovel.tsx";
import * as $$$$$$4 from "./sections/ContactForm.tsx";
import * as $$$$$$5 from "./sections/ContactInformation.tsx";
import * as $$$$$$6 from "./sections/Curadoria.tsx";
import * as $$$$$$7 from "./sections/FloatingActionButtons/BackToTop.tsx";
import * as $$$$$$8 from "./sections/FloatingActionButtons/SendEmail.tsx";
import * as $$$$$$9 from "./sections/FloatingActionButtons/Whatsapp.tsx";
import * as $$$$$$10 from "./sections/Footer.tsx";
import * as $$$$$$11 from "./sections/Header.tsx";
import * as $$$$$$12 from "./sections/Hero.tsx";
import * as $$$$$$13 from "./sections/ItWorks.tsx";
import * as $$$$$$14 from "./sections/PageTitle.tsx";
import * as $$$$$$15 from "./sections/PropertyDetails.tsx";
import * as $$$$$$16 from "./sections/RelatedPosts.tsx";
import * as $$$$$$17 from "./sections/RichText.tsx";
import * as $$$$$$18 from "./sections/SearchResult.tsx";
import * as $$$$$$19 from "./sections/Services.tsx";
import * as $$$$$$20 from "./sections/Shelf.tsx";
import * as $$$$$$21 from "./sections/Theme/Theme.tsx";
import * as $$$$$$22 from "./sections/Wishlist.tsx";

const manifest = {
  "sections": {
    "site/sections/BannerCTA.tsx": $$$$$$0,
    "site/sections/BlogPost.tsx": $$$$$$1,
    "site/sections/BlogPosts.tsx": $$$$$$2,
    "site/sections/BuscaImovel.tsx": $$$$$$3,
    "site/sections/ContactForm.tsx": $$$$$$4,
    "site/sections/ContactInformation.tsx": $$$$$$5,
    "site/sections/Curadoria.tsx": $$$$$$6,
    "site/sections/FloatingActionButtons/BackToTop.tsx": $$$$$$7,
    "site/sections/FloatingActionButtons/SendEmail.tsx": $$$$$$8,
    "site/sections/FloatingActionButtons/Whatsapp.tsx": $$$$$$9,
    "site/sections/Footer.tsx": $$$$$$10,
    "site/sections/Header.tsx": $$$$$$11,
    "site/sections/Hero.tsx": $$$$$$12,
    "site/sections/ItWorks.tsx": $$$$$$13,
    "site/sections/PageTitle.tsx": $$$$$$14,
    "site/sections/PropertyDetails.tsx": $$$$$$15,
    "site/sections/RelatedPosts.tsx": $$$$$$16,
    "site/sections/RichText.tsx": $$$$$$17,
    "site/sections/SearchResult.tsx": $$$$$$18,
    "site/sections/Services.tsx": $$$$$$19,
    "site/sections/Shelf.tsx": $$$$$$20,
    "site/sections/Theme/Theme.tsx": $$$$$$21,
    "site/sections/Wishlist.tsx": $$$$$$22,
  },
  "actions": {
    "site/actions/createClient.ts": $$$$$$$$$0,
    "site/actions/getImoveis.ts": $$$$$$$$$1,
  },
  "apps": {
    "site/apps/deco/blog.ts": $$$$$$$$$$$0,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$1,
    "site/apps/deco/records.ts": $$$$$$$$$$$2,
    "site/apps/site.ts": $$$$$$$$$$$3,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
